apiVersion: v1
kind: Namespace
metadata:
  name: pong-namespace
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pong-app
  namespace: pong-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pong-app
  template:
    metadata:
      labels:
        app: pong-app
    spec:
      containers:
      - name: pong-app
        image: giovaz94/pong-app:latest
        ports:
        - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: pong-service
  namespace: pong-namespace
spec:
  selector:
    app: pong-app
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
  type: ClusterIP