apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-redis
  template:
    metadata:
      labels:
        app: app-redis
    spec:
      containers:
      - name: redis
        image: redis:latest
        ports:
        - containerPort: 6379
      - name: app
        image: giovaz94/simple-flask:latest
        ports:
        - containerPort: 80
        env:
        - name: APP_NAME
          value: "Python App"
        - name: REDIS_HOST
          value: "localhost"
        - name: REDIS_PORT
          value: "6379"
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: app-redis
  ports:
    - protocol: TCP
      port: 80
      nodePort: 30080
  type: NodePort